"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^h1_^!&vys4=#&rz+0pm-ul@=uih23(47bgm(erw68**(l&f19'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "rest_framework",
     "corsheaders",
     
    "apps.products",
    "apps.addresses",
    
    "apps.categories",
    
    "apps.payments",
    # "apps.reviews",
    # "apps.wishlist",
    "apps.orders",
    "apps.checkout",
    "apps.cart",
    
    "apps.accounts",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    
    # homepage
    
    "apps.hero",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = "accounts.User"


# rest framework setup
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Next.js
    "http://localhost:8000",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),      # or 12 hours
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,

    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# stripe payment integrations# Payment Settings
# =========================
# Payment Gateway Settings
# =========================


# Stripe

STRIPE_SECRET_KEY = config(
    "STRIPE_SECRET_KEY",
    default="sk_test_dummy_key"
)

STRIPE_PUBLIC_KEY = config(
    "STRIPE_PUBLIC_KEY",
    default="pk_test_dummy_key"
)

STRIPE_WEBHOOK_SECRET = config(
    "STRIPE_WEBHOOK_SECRET",
    default=""
)


# =========================
# Khalti
# =========================

KHALTI_SECRET_KEY = config(
    "KHALTI_SECRET_KEY",
    default="test_secret_key"
)

KHALTI_PUBLIC_KEY = config(
    "KHALTI_PUBLIC_KEY",
    default="test_public_key"
)

KHALTI_BASE_URL = config(
    "KHALTI_BASE_URL",
    default="https://a.khalti.com/api/v2"
)


# =========================
# eSewa
# =========================
# =========================
# eSewa
# =========================

ESEWA_SECRET_KEY = config(
    "ESEWA_SECRET_KEY",
    default="test_esewa_secret_key"
)

ESEWA_MERCHANT_CODE = config(
    "ESEWA_MERCHANT_CODE",
    default="EPAYTEST"
)

ESEWA_BASE_URL = config(
    "ESEWA_BASE_URL",
    default="https://rc-epay.esewa.com.np/api/epay/main/v2/form"
)


# =========================
# General Payment
# =========================

PAYMENT_CURRENCY = config(
    "PAYMENT_CURRENCY",
    default="NPR"
)


# settings.py
from decimal import Decimal

DEFAULT_SHIPPING_COST = Decimal("100.00")
DEFAULT_TAX_RATE = Decimal("0.13")