# Generated by Django 6.1 on 2026-08-22 17:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this deal can be used. Leave empty for unlimited usage.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority deals are selected first when multiple deals apply to a product.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='deals.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='products.product')),
            ],
            options={
                'db_table': 'deal_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='deals', through='deals.DealProduct', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='dealproduct',
            index=models.Index(fields=['deal', 'product'], name='deal_product_idx'),
        ),
        migrations.AddIndex(
            model_name='dealproduct',
            index=models.Index(fields=['product'], name='deal_product_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealproduct',
            constraint=models.UniqueConstraint(fields=('deal', 'product'), name='unique_deal_product'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='deal_active_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['slug'], name='deal_slug_idx'),
        ),
    ]
